name: build

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest samba
        run: curl -o samba.tar.gz https://download.samba.org/pub/samba/samba-latest.tar.gz

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: AMD build
        run: docker compose build dc1

      - name: ARM build
        run: ./dev/arm64/build.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and publish
        run: ./dev/update-tags-and-push-to-dockerhub.sh
